### ISSUE TITLE
Upgrade InfluxDB support

### ISSUE THREAD

**Issue by MartinSeeler** [paulgoldbaum/scala-influxdb-client#17]
I've tried the client with the latest release (0.11) of InfluxDB, but it seems that some API calls do not work any more. For example, the `database.exists()` always returns true for some reason. On the other hand, inserting and querying datapoints seems to work properly. 

Can please upgrade the provided version of InfluxDB to the latest 0.11 version? Also, providing a lookup table which client version works up to which version of InfluxDB would be great.

**Comment by paulgoldbaum** [comment]
Thanks for the report, will look into it.

**Comment by paulgoldbaum** [comment]
@MartinSeeler I've tried to reproduce this with the latest stable version(0.12.2) and everything works as expected (except writing to a non-existent database because of a bug in influxdb itself). I tested database.exists() specifically and didn't find any issues. Could you re-test or send me a test case?
